
stages:
  - test
  - build
  - security-review
  - development
  - qa
  - prod

cache:
  paths:
    - .cargo/
    - .cache/sccache

build:
  stage: test
  image: rustdocker/rust:nightly
  script:
    - /root/.cargo/bin/cargo test
    - /root/.cargo/bin/cargo build --release
    - echo "Attest this image (using Build attestor)"
  artifacts:
    expire_in: 30 minutes
    paths:
      - target/release/hello_world

build-and-push-image:
  stage: build
  image: docker:19.03.8
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    FULL_IMAGE: gcr.io/${GOOGLE_PROJECT_ID}/hello-world:${CI_COMMIT_SHORT_SHA}
  services:
    - docker:19.03.8-dind
  script:
    - mkdir keys
    - echo $GOOGLE_BUILD_GSA | base64 -d > ${CI_PROJECT_DIR}/keys/key-file.json
    - cat ${CI_PROJECT_DIR}/keys/key-file.json | docker login -u _json_key --password-stdin https://gcr.io
    - docker build -t ${FULL_IMAGE} .
    - docker push ${FULL_IMAGE}
    - export IMAGE_ID=$(docker image inspect ${FULL_IMAGE} --format '{{ .ID }}')
    - |
        cat > image-details.txt <<EOL
        image: ${FULL_IMAGE} digest: ${IMAGE_ID}
        EOL
    - cat image-details.txt
  artifacts:
    expire_in: 24 hours
    paths:
      - image-details.txt

# docker image inspect gcr.io/$PROJECT_ID/binauthz-test:latest --format '{{ .ID }}' > image-digest.txt && cat image-digest.txt

security-audit:
  stage: security-review
  image: alpine:latest # TODO: Change to gcloud image or something like that
  script:
    - cat image-details.txt
    - export IMAGE_PATH=$(cat image-details.txt | awk '{print $2 }')
    - export IMAGE_DIGEST=$(cat image-details.txt | awk '{print $4 }')
    - echo "Get Public Key for 'security' attestor"
    - echo "Emulate a 'security' audit"
    - echo "Attest image is secure (using Security Attestor)"
#
    # - gcloud container binauthz attestations create \
    #     --artifact-url="${IMAGE_PATH}@${IMAGE_DIGEST}" \
    #     --attestor="projects/${PROJECT_ID}/attestors/${ATTESTOR}" \
    #     --signature-file=/tmp/ec_signature \
    #     --public-key-id="${PUBLIC_KEY_ID}"


deploy-development:
  stage: development
  environment:
    name: development
  script:
    - echo "Emulate deploy to development"

deploy-qa:
  stage: qa
  when: manual
  environment:
    name: qa
  script:
    - echo "Attest the image has been in Development and passed (Development Attestor)"
    - echo "Emulate deploy to qa"

deploy-production:
  stage: prod
  when: manual
  environment:
    name: prod
  script:
    - echo "Attest the image has been in QA and passed (QA Attestor)"
    - echo "Emulate deploy to prod"
