apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- resource-limits.yaml
- deployment.yaml
namespace: default
namePrefix: dev-
commonLabels:
  environment: development
resources:
- ../../base