apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world
spec:
  type: ClusterIP # maybe LoadBalancer for example purposes?
  ports:
    - port: 8080
  selector:
    app: hello-world-app